// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");

function fibonacciTermsBelowMax(prev1, prev2) {
  var sum = prev1 + prev2 | 0;
  if (sum > 4000000) {
    return /* :: */[
            prev1,
            /* :: */[
              prev2,
              /* [] */0
            ]
          ];
  } else {
    return /* :: */[
            sum,
            fibonacciTermsBelowMax(prev2, sum)
          ];
  }
}

var allTerms = fibonacciTermsBelowMax(2, 4);

console.log($$Array.of_list(allTerms));

var max = 4000000;

exports.max                    = max;
exports.fibonacciTermsBelowMax = fibonacciTermsBelowMax;
exports.allTerms               = allTerms;
/* allTerms Not a pure module */
